abarocks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("patreon", views.patreon, name="patreon"),
    path("login/", views.login, name="login"),
    path("blog/", include("blog.urls")),
    path("quizzes/", include("quiz.urls")),
    path("learn/", include("learn.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()

admin.site.site_title = "ABA.rocks Administration"
admin.site.site_header = "ABA.rocks administration"

blog/urls.py
from django.urls import path, include, re_path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.Posts.as_view(), name="blog-posts"),
    path("<int:post_id>/", views.post, name="blog-post"),
]

learn/urls.py
from django.urls import path

from . import views

app_name = "learn"
urlpatterns = [
    path("courses/", views.CourseIndex.as_view(), name="course-index"),
    path("<str:code>/", views.course_landing_page, name="course-landing_page"),
    path(
        "<str:code>/tasklist/",
        views.TaskListView.as_view(),
        name="tasklist-landing-page",
    ),
    path("<str:code>/course/", views.lesson_page, name="lesson-page"),
    path(
        "task/change/options",
        views.task_changeform_options,
        name="task-changeform-options",
    ),
    path("task/change/area_name", views.get_area_name, name="get-area-name"),
]

learn/models.py
from django.db import models
from django.contrib.auth.models import User

from django_ckeditor_5.fields import CKEditor5Field


# Create your models here.
class Course(models.Model):
    """Competencies, subjects, and topics (e.g., BCBA, RBT, Feeding Therapy, etc.)"""

    # TODO: Add relation in pages
    code = models.CharField(max_length=10, unique=True, primary_key=True)
    name = models.CharField(max_length=50)
    image = models.CharField(null=True, max_length=250)
    description = models.TextField(null=True)
    course_data = models.JSONField(null=True, blank=True)

    class Meta:
        db_table_comment = "The competency, license, or topic of interest"

    def __str__(self):
        return self.name

    def get_task_list(self) -> dict:
        """Returns the entire BACB Task List for RBTs, BCBAs, or BCaBAs"""
        if self.code == "RBT" or self.code == "BCBA" or self.code == "BCaBA":
            tasks = self.tasks.all().order_by("area", "task")
            task_list = {}
            for task in tasks:
                area = f"{task.area.letter}: {task.area.area}"
                task_name = f"{task.area.letter}-{task.task}"
                if area in task_list:
                    task_list[area][task_name] = task.task_desc
                else:
                    task_list[area] = {task_name: task.task_desc}
            return task_list
        else:
            pass


class ContentArea(models.Model):
    slug = models.SlugField(unique=True, primary_key=True)
    license = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="content_areas"
    )
    letter = models.CharField(max_length=1)
    section = models.IntegerField(null=True, blank=True)
    area = models.CharField(max_length=50)
    weight = models.IntegerField()

    class Meta:
        db_table_comment = "The content areas for each Course"
        default_related_name = "content_areas"

    def __str__(self):
        if self.section:
            return f"{self.license.code}, Section {self.section}, Area {self.letter}: {self.area}"
        else:
            return f"{self.license.code}, Area {self.letter}: {self.area}"

    def save(self, *args, **kwargs):
        if self.section:
            self.slug = f"{self.license.code}-{self.section}-{self.letter}"
        else:
            self.slug = f"{self.license.code}-{self.letter}"
        return super(ContentArea, self).save(*args, **kwargs)


class TaskManager(models.Manager):
    """Manager to return natural key of Task"""

    def get_by_natural_key(self, license, area, task):
        return self.get(license=license.code, area=area, task=task)


class Task(models.Model):
    """BACB Task List items"""

    slug = models.SlugField(unique=True, primary_key=True)
    license = models.ForeignKey(Course, on_delete=models.CASCADE)
    area = models.ForeignKey(
        ContentArea,
        on_delete=models.CASCADE,
    )
    task = models.IntegerField()
    task_desc = models.TextField()

    objects = TaskManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["license", "area", "task"], name="unique_tasks"
            )
        ]
        db_table_comment = "Tasks for RBT, BCaBA, and BCBA according to the BACB"
        default_related_name = "tasks"

    def __str__(self):
        return f"{self.license.code} Task List: Item {self.area.letter}-{self.task}"

    def natural_key(self):
        return (self.license, self.area, self.task)

    def save(self, *args, **kwargs):
        self.slug = f"{self.license.code}-{self.area.letter}-{self.task}"
        return super(Task, self).save(*args, **kwargs)


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    area = models.ForeignKey(ContentArea, on_delete=models.CASCADE)
    page = models.IntegerField()
    title = models.CharField(max_length=100)
    content = CKEditor5Field()

    class Meta:
        models.UniqueConstraint(fields=["course", "page"], name="unique_lessons")
        db_table_comment = "Lesson pages for each course"
        default_related_name = "lessons"

    def __str__(self):
        return f"{self.course} Lesson {self.page}"

learn/forms.py
from django.forms import ModelForm
from django.forms.widgets import Select
from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        exclude = ["slug"]
        widgets = {
            "license": Select(
                attrs={
                    "hx-get": "/learn/task/change/options",
                    "hx-target": "#id_area",
                    "hx-swap": "outerHTML",
                    # "hx-indicator": "",
                }
            )
        }

learn/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from django.template.response import TemplateResponse
from django.views.generic import ListView

from .models import Course, Lesson, Task, ContentArea
from pages.models import Pages
from core.decorators import htmx_required


class CourseIndex(ListView):
    model = Course
    context_object_name = "Courses"
    template_name = "learn/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context["page"] = Pages.objects.get("Courses")
        return context


@login_required
def course_landing_page(request, code) -> HttpResponse:
    # page = Pages.objects.get(f"{code} Lesson Intro")
    course = get_object_or_404(Course, pk=code)
    return render(
        request,
        "learn/unit_landing_page.html",  # TODO: Check tempalte name
        {
            "learn_topic": course,
            # "page": page,
        },
    )


class TaskListView(ListView):
    model = Course
    template_name = "learn/task_list.html"

    def get_queryset(self):
        queryset = get_object_or_404(Course, code=self.kwargs["code"])
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["task_list"] = Course.objects.get(
            code=self.kwargs["code"]
        ).get_task_list()
        context["license"] = self.kwargs["code"]
        return context


def lesson_page(request, course) -> HttpResponse:
    page = request.GET.get("page")
    lesson = Lesson.objects.get(course=course, page=page)
    # TODO: Determine logic for saving sessions and handling users
    return render(
        request,
        "",  # TODO: Replace with template name
        {"lesson": lesson, "page": page},
    )


def _next_page(request, course) -> HttpResponse:
    # Pull current page from session/profile
    # Increment page # and query for ID
    pass


@htmx_required
def task_changeform_options(request):
    if request.GET.get("license") == "BCaBA":
        course_filter = ContentArea.objects.filter(license="BCBA")
    else:
        course_filter = ContentArea.objects.filter(license=request.GET.get("license"))
    if course_filter.exists():
        areas = {}
        for index, slug in enumerate(course_filter.values_list("slug", flat=True)):
            areas[slug] = str(course_filter[index])
        return TemplateResponse(
            request,
            "learn/partial/_options.html",
            {"areas": areas},
        )
    else:
        pass


def get_area_name(request):
    if request.htmx:
        area = (
            Task.objects.filter(area=request.GET.get("area"))
            .values_list("area_name", flat=True)
            .distinct()
        )
        return area

learn/templates/learn/account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container">
  Account content here.
</div>


<script>
  function resize() {
    // Resize post container for desktop
    if (window.screen.width <= 576) {
      document.querySelector("#post_container").style.visibility = "visible";
    } else if ( window.screen.width > 576 && window.screen.width <= 900) {
      document.querySelector("#post_container").style.marginLeft = window.screen.width * 0.22 + "px";
      document.querySelector("#post_container").style.visibility = "visible";
      document.querySelector("#carousel").style.marginLeft = window.screen.width * 0.22 + "px";
    } else if ( window.screen.width > 900 && window.screen.width <= 1200) {
      document.querySelector("#post_container").style.marginLeft = window.screen.width * 0.165 + "px";
      document.querySelector("#post_container").style.visibility = "visible";
      document.querySelector("#carousel").style.marginLeft = window.screen.width * 0.165 + "px";
    } else if ( window.screen.width >= 900 && window.screen.width <= 1200) {
      document.querySelector("#post_container").style.marginLeft = window.screen.width * 0.185 + "px";
      document.querySelector("#post_container").style.visibility = "visible";
      document.querySelector("#carousel").style.marginLeft = window.screen.width * 0.185 + "px";
    } else {
      document.querySelector("#post_container").style.marginLeft = window.screen.width * 0.225 + "px";
      document.querySelector("#post_container").style.visibility = "visible";
      document.querySelector("#carousel").style.marginLeft = window.screen.width * 0.125 + "px";
    }
  }

  window.onload = function () { 
    resize();
  }

  window.onresize = function(event) {
      resize();
  };
</script>

{% endblock %}

learn/templates/learn/change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% block extrahead %}{{ block.super }}
<script src="{% url 'admin:jsi18n' %}"></script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" href="{% static "admin/css/forms.css" %}">{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% translate 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; {% if has_view_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% blocktranslate with name=opts.verbose_name %}Add {{ name }}{% endblocktranslate %}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change and not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
      {% change_form_object_tools %}
    {% endblock %}
  </ul>
{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}{% if form_url %}action="{{ form_url }}" {% endif %}method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1">{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}">{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% blocktranslate count counter=errors|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktranslate %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

<div>
    <label for="license">License</label>
    <select name="license" id="license" hx-get="task/change/options" hx-target="#area" hx-indicator=".htmx-indicator">
      <option value="">Select a license</option>
      {% for key, value in licenses.items %}
        <option value="{{ key }}">{{ value }}</option>
      {%  endfor %}
    </select>
</div>
<div>
    <label for="area">Area</label>
    <select id="area" name="area" hx-swap="innerHTML" hx-get="task/change/options" hx-target="#area_name" hx-indicator=".htmx-indicator">
      {% block options %}
      <option value=""></option>
      {% for key, value in options.items %}
      <option value="{{ key }}">{{ value }}</option>
      {% endfor %}
      {% endblock %}
    </select>
    <label for="area_name">Area Name</label>
    <input type="text" value="" readonly="readonly" id="area_name" name="area_name"/>
    <img class="htmx-indicator" width="20" src="{% static "/img/bars.svg" %}" alt="loader bars">
</div>
{% block admin_change_form_document_ready %}
    <script id="django-admin-form-add-constants"
            src="{% static 'admin/js/change_form.js' %}"
            {% if adminform and add %}
                data-model-name="{{ opts.model_name }}"
            {% endif %}
            async>
    </script>
{% endblock %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}

learn/templates/learn/course_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="content_container" class="container" style="padding: 2.5%; border: 1px solid red;">

  <div class="row">
    <div class="col-12 lms-title">
      <h2>The Task-List Takedown!</h2>
    </div>

    <div class="w-100" style="height: 2rem;"></div>

    <div class="col lms-resume">

      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"> {{ user.profile.last_lesson_page }} </h5>
          <h6 class="card-subtitle mb-2 text-muted">Pick up where you left off</h6>
          <img class="img-fluid" src="https://www.aba.rocks/{{ user.profile.last_lesson_page.pic }}" alt="User's Profile Picture">
          <div class="w-100" style="height: 1rem;"></div>
          <p class="card-text">
            {{ user.profile.last_lesson_page.body|safe|truncatewords_html:user.profile.last_lesson_page.snippet_size }}
          </p>
          <a href="{% url 'course_index' %}" class="btn btn-info text-white">Study</a>
          <!-- /learn/unit/{{user.profile.last_lesson_page.id}} -->
        </div>
      </div>
    </div>

    <div class="col-8 lms-progress-chart">
      <div class="container" style="height: 400px;width:400px;">
        <canvas id="myChart"></canvas>
      </div>
    </div>

    <div class="w-100" style="height: 5rem;"></div>

    <div class="col-12 lms-all-units">

      <h2>RBT Study Materials</h2>
      <p>
        Let's cover the task list, item-by-item - then, take practice quizzes to get yourself ready for the RBT exam
      </p>
      <p class="text-info">
        <u>NOTE</u>: this course <b><u>DOES NOT</u></b> count towards your 40 hour training requirement for the RBT exam -- this is intended as a free, supplementary resource to build your skills and confidence in behavior analysis, and help get you ready for the BACB's RBT exam. There's also no substitute for real-world practice - real-world practice with a competent BCBA is strongly suggested.
      </p>

      <div class="w-100" style="height: 1rem;"></div>

      <p>
        <img src="https://aba.rocks/static/img/BACB-Emblem-new.png" alt="BACB Emblem" class="img-thumbnail float-left" height="50px" width="50px" style="margin-right: 10px;">
        <p class="text-muted">
          The RBT Task list and BACB emblem are Copyright © 1998-2019 the Behavior Analyst Certification Board, Inc., (BACB), ALL RIGHTS RESERVED. 
        </p>
      </p>

      <div class="w-100" style="height: 2rem;"></div>

      <div class="accordion" id="lms-unit-accordion">
        
        {% for unit in units %}
        <div class="card">
          <div class="card-header" id="headingOne" type="button" data-toggle="collapse" data-target="#collapse-unit-{{ unit.id }}" aria-expanded="true" aria-controls="collapseOne">
            <h5 class="mb-0">
              <button class="btn btn-link">
                {{ unit.unit_name }}
              </button>
            </h5>
          </div>

          <div id="collapse-unit-{{ unit.id }}" class="collapse" aria-labelledby="headingOne" data-parent="#lms-unit-accordion">
            <div class="card-body">
              {{ unit.unit_description | safe }}
              <br />
              <a href="unit/{{ unit.id }}" class="btn btn-info">Study</a>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>


    </div>

  </div>

</div>
{% endblock %}

learn/templates/learn/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Course Index{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center align-items-start flex-container">
            {% for course in Courses %}
            <div class="p-2 bd-highlight">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{% static course.image %}" alt="Card image cap">
                    <div class="text-center card-body">
                        <h5 class="card-title">{{ course.name }}</h5>
                        <p class="card-text">{{ course.description|truncatechars:50 }}</p>
                        <a href="#" class="btn btn-primary">Resume</a>
                        <a href="#" class="btn btn-secondary">Course Overview</a>
                        <a href="{% url 'learn:tasklist-landing-page' code=course.code %}" class="btn btn-secondary">Task List</a>
                    </div>
                </div>
            </div>
            {% endfor %}
    </div>
{% endblock content %}

learn/templates/learn/learn_topic.html
{% extends 'base.html' %}

{% block content %}{% block mobile-content %}
    <div id="post_container" class="post container" style="padding: 0 2.5% 5% 2.5%; visibility: hidden;margin-top: 25px;">
      <div class="row">

        <div class="calendar-icon col-1">
        </div>

        <div class="col-12" style="margin-left: 0px;">

          <h1> {{ page.title }} </h1>
          <br />

          {{ page.text | safe }}

          <br />
          <br />
          <br />
          <br />
        </div>


      <div id="disqus_thread" class="post-text col-12"></div>
      <script>

        function resize() {
          // Resize post container for desktop
          if (window.screen.width <= 576) {
            document.querySelector("#post_container").style.visibility = "visible";
          } else if ( window.screen.width >= 576 && window.screen.width <= 900) {
            document.querySelector("#post_container").style.marginLeft = window.screen.width * 0.20 + "px";
            document.querySelector("#post_container").style.visibility = "visible";
          } else if ( window.screen.width >= 900 && window.screen.width <= 1200) {
            document.querySelector("#post_container").style.marginLeft = window.screen.width * 0.165 + "px";
            document.querySelector("#post_container").style.visibility = "visible";
          }    else {
            document.querySelector("#post_container").style.visibility = "visible";
          }
        }

        window.onload = function () { 
          resize();
        }

        window.onresize = function(event) {
            resize();
        };

        /**
        *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
        *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
        var disqus_config = function () {
            this.page.url = '{{ request.build_absolute_uri }}{{ object.get_absolute_url }}';
            this.page.identifier = '{{ page.id }}';
            this.page.title = '{{ page.title }}';
        };

        (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://https-aba-rocks.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
        })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

      </div>
    </div>
{% endblock %}{% endblock %}

learn/templates/learn/task_list.html
{% block content %}
{{ license }} Task List
{% for area, task in task_list.items %}
<table>
<caption>
  {{ area }}
</caption>
  <tr>
    <th scope="col">Task</th>
    <th scope="col">Description</th>
  </tr>
  <tr>
    {% for task, description in task.items %}
    <td>{{ task }}</td>
    <td>{{ description }}</td>
    {% endfor %}
  </tr>
</table>
{% endfor %}
{% endblock %}

learn/templates/learn/unit_landing_page.html
{% extends 'base.html' %}

{% block content %}{% block mobile-content %}
    <div id="post_container" class="post container" style="padding: 0 2.5% 5% 2.5%;margin-top: 25px;">
      <div class="row">

        <div class="calendar-icon col-1">
        </div>

        <div class="col-2"> </div>

        <div class="col-10">
          
          <h2>
            <strong>
              {{ learn_topic.title }}
            </strong>
          </h2>
          
          <h4 class="text-muted">Test {{ learn_topic.lesson_unit }}</h4>

          <br />

          {{ learn_topic.body | safe }}


          <br />
          <br />


          <hr>
          <h3>
            Let's Practice:
          </h3>

          <br />
          <br />

          <strong>
            Lesson Progress
          </strong>
          <div class="progress">
            <div id="progress-bar" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
          </div>
          <i class="text-muted">Complete the unit quizzes below to progress forward in this unit, or click here to <a href="#" onClick="markComplete()"><b>mark this unit as complete</b></i></a>


          <br />
          <br />

          {% if learn_topic.lesson_quizzes %}
            <ul id="completed_quizzes">
            {% for quiz in learn_topic.lesson_quizzes.all %}
              <li><a id="quiz_{{quiz.id}}" href="/quiz/{{quiz.form_unit.id}}/form_{{quiz.id}}/">{{quiz.form_name}}</a></li>
            {% endfor %}
            </ul>
          {% endif %}

          <br />
          <br />
          <br />

          <div class="container" style="text-align: center;">      
            <h3>
              Next Up:
            </h3>

            <br />

            {% if learn_topic.last_lesson %}
              <a class="btn btn-primary" href="{{ learn_topic.last_lesson.id }}">
                <i class="fas fa-step-backward"></i>
                 Last Unit: 
                <strong>
                  {{ learn_topic.last_lesson }}
                </strong>
              </a>
            {% endif %}

            {% if learn_topic.next_lesson %}
              <a class="btn btn-primary" href="{{ learn_topic.next_lesson.id }}">
                Next Unit: 
                <strong>
                  {{ learn_topic.next_lesson }}
                  <i class="fas fa-step-forward"></i>
                </strong>
              </a>
            {% endif %}
          </div>

          <hr> 
          <br />
          <br />
          <br />
          <br />

        </div>

      </div>

      <div id="disqus_thread" class="post-text col-12"></div>

    </div>

      
      <script>
        function checkProgress() {
          //var progress = "{{ user.profile.user_quiz_forms_completed.all }}";
          var completed_quiz_ids = [];
          {% if user.profile.user_quiz_forms_completed.all %}
            {% for quiz in user.profile.user_quiz_forms_completed.all %}
              completed_quiz_ids["{{forloop.counter0}}"] = "{{quiz.id}}";
            {% endfor %}
          {% endif %}

          var lesson_quizzes = [];
           {% if learn_topic.lesson_quizzes %}
            {% for quiz in learn_topic.lesson_quizzes.all %}
              lesson_quizzes["{{forloop.counter0}}"] = "{{quiz.id}}"
            {% endfor %}
          {% endif %}

          count_completed_lesson_quizzes = 0;
          
          for ( i = 0; i < lesson_quizzes.length; i++ ) {
            if ( completed_quiz_ids.includes(lesson_quizzes[i]) ) {
              count_completed_lesson_quizzes++;
            }
          }

          var progress = (100*count_completed_lesson_quizzes/lesson_quizzes.length)+'%';
          recordProgress(progress);
          
        }
        checkProgress();


        function markComplete() {
          recordProgress("100%");
          alert('{{learn_topic.lesson_unit}} - marked complete!')
        }


        function recordProgress(progress) {
          document.getElementById('progress-bar').style.width = progress;
        }


        function resize() {
          // Resize post container for desktop
          if (window.screen.width <= 576) {
            document.querySelector("#post_container").style.visibility = "visible";
          } else if ( window.screen.width >= 576 && window.screen.width <= 900) {
            document.querySelector("#post_container").style.marginLeft = window.screen.width * 0.20 + "px";
            document.querySelector("#post_container").style.visibility = "visible";
          } else if ( window.screen.width >= 900 && window.screen.width <= 1200) {
            document.querySelector("#post_container").style.marginLeft = window.screen.width * 0.265 + "px";
            document.querySelector("#post_container").style.visibility = "visible";
          }    else {
            document.querySelector("#post_container").style.visibility = "visible";
          }
        }

        window.onload = function () { 
          resize();
        }

        window.onresize = function(event) {
            resize();
        };
      </script>
      

      {% include "disqus.html" %}
                            

      </div>
    </div>
{% endblock %}{% endblock %}