abarocks/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("patreon", views.patreon, name="patreon"),
    path("login/", views.login, name="login"),
    path("blog/", include("blog.urls")),
    path("quizzes/", include("quiz.urls")),
    path("learn/", include("learn.urls")),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.ENABLE_DEBUG_TOOLBAR:
    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()

admin.site.site_title = "ABA.rocks Administration"
admin.site.site_header = "ABA.rocks administration"

blog/urls.py
from django.urls import path, include, re_path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.Posts.as_view(), name="blog-posts"),
    path("<int:post_id>/", views.post, name="blog-post"),
]

learn/urls.py
from django.urls import path

from . import views

app_name = "learn"
urlpatterns = [
    path("courses/", views.CourseIndex.as_view(), name="course-index"),
    path("<str:code>/", views.course_landing_page, name="course-landing_page"),
    path(
        "<str:code>/tasklist/",
        views.TaskListView.as_view(),
        name="tasklist-landing-page",
    ),
    path("<str:code>/course/", views.lesson_page, name="lesson-page"),
    path(
        "task/change/options",
        views.task_changeform_options,
        name="task-changeform-options",
    ),
    path("task/change/area_name", views.get_area_name, name="get-area-name"),
]

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{ post.title }} {% endblock title %}
{% block content %}
<div class="jumbotron jumbotron-fluid py-4">
	<div class="container">
	<h1 class="display-4">About ABA.Rocks</h1>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</div>
</div>
{% endblock content %}

templates/base.html
{% load static django_bootstrap5 django_htmx %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ABA.Rocks is a behavior analysis blog dedicated to the science of learning." />

    <!-- Pinterest Claim -->
    <meta name="p:domain_verify" content="4d2813b6def4c45e881bd8e54cfbb0d0" />

    <title>{% block title %}{% endblock %}</title>

    <!-- <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script> -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    {% django_htmx_script %}

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-98470698-1', 'auto');
        ga('send', 'pageview');
    </script>

    <meta name="theme-color" content="#ffffff">
  
  {% block extra-head %}{% endblock %}

</head>
	<body>
		<header id="header">
			{% include "header.html" %}
		</header>
		<div id="content">
			{% block content %}{% endblock %}
		</div>
		<footer id="footer">
			{% include "footer.html" %}
		</footer>
	</body>
</html>

templates/content.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{ post.title }} {% endblock title %}
{% block content %}
<div class="jumbotron jumbotron-fluid py-4">
	<div class="container">
	<h1 class="display-4">{{ post.title }}</h1>
	{% autoescape off %}
		{{ Post.text }}
	{% endautoescape %}
	</div>
</div>
{% endblock content %}

templates/disqus.html
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    var disqus_config = function () {
        this.page.url = 'https://www.aba.rocks{{ request.path }}';
        this.page.identifier = '{{ page.id }}';
        this.page.title = '{{ page.title }}';
    };

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://https-aba-rocks.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

templates/head.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load django_htmx %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ABA.Rocks is a behavior analysis blog dedicated to the science of learning." />

    <!-- Pinterest Claim -->
    <meta name="p:domain_verify" content="4d2813b6def4c45e881bd8e54cfbb0d0" />

    <title>{% block title %}{% endblock title %}ABA Rocks: A Behavior Analysis Blog</title>

    <!-- <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script> -->
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://unpkg.com/htmx-ext-debug@2.0.0/debug.js"></script>
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-98470698-1', 'auto');
        ga('send', 'pageview');
    </script>

    <meta name="theme-color" content="#ffffff">

</head>

templates/header.html
<nav class="navbar navbar-dark navbar-expand-lg" style="background-color: #ff9400;">
    <div class="container-fluid">
    <a class="navbar-brand" style="color: #fff; font-weight: bold;" href="{% url 'home' %}">ABA.Rocks</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa-solid fa-bars fa-xl" style="color: #ffffff;"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="font-weight: bold;">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'learn:course-index' %}">Learn</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'blog:blog-posts' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'patreon' %}">Patreon</a>
            </li>
            <li class="nav-item dropdown" style="font-weight: bold;">
                <a class="nav-link dropdown-toggle" href="{% url 'blog:blog-posts' %}" style="color: #fff" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Study by Certification
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="">RBT</a></li>
                    <li><a class="dropdown-item" href="">BCaBA</a></li>
                    <li><a class="dropdown-item" href="">BCBA</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="">Study something else here</a></li>
                </ul>
            </li>
        </ul>
    </div>
    </div>
</nav>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}ABA Rocks: A Behavior Analysis Blog{% endblock %}
{% block content %}
  {% include "blog/posts.html" %}
{% endblock %}

templates/login.html
{% load static %}

{% block login %}
    <!-- Hero -->
    <div class="px-4 py-4 my-0 text-center">
        <img class="d-block mx-auto mb-2" src="{% static 'img/studying_quiz.png' %}" alt="" width="216" height="171">
        <h1 class="display-5 fw-bold text-body-emphasis">ABA.Rocks</h1>
        <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">The world's largest free platform for learning ABA - from parent to practitioner.</p>
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <button type="button" class="btn btn-primary btn-lg px-4 gap-3">Learn</button>
            <button type="button" class="btn btn-outline-secondary btn-lg px-4">Log In</button>
        </div>
        </div>
    </div>
{% endblock login %}

templates/patreon.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{ post.title }} {% endblock title %}
{% block content %}
<div class="jumbotron jumbotron-fluid py-4">
	<div class="container">
	<h1 class="display-4">Support ABA.Rocks</h1>
		Patreon
		<br>
		Ko-Fi
	</div>
</div>
{% endblock content %}